[tools]
bat = "latest"
bottom = "latest"
chezmoi = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
git-cliff = "latest"
git-lfs = "latest"
gitui = "latest"
hk = "latest"
jaq = "latest"
jq = "latest"
navi = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
television = "latest"
tlrc = "latest"
typst = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
