[tools]
"aqua:eza-community/eza" = "latest"
"aqua:openai/codex" = "latest"
atuin = "latest"
bat = "latest"
bun = "latest"
chezmoi = "latest"
claude = "latest"
fastfetch = "latest"
fd = "latest"
git-lfs = "latest"
jaq = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
ripgrep = "latest"
rumdl = "latest"
starship = "latest"
television = "latest"
typst = "latest"
uv = "latest"
zoxide = "latest"
